"""Write a Python program that can suspend execution of a given script a given number of seconds. 
Sample Output:
Sorry, Slept for 3 seconds...
Sorry, Slept for 3 seconds...
Sorry, Slept for 3 seconds...
Sorry, Slept for 3 seconds... """ 
